"""empty message

Revision ID: df093e4cc05f
Revises: 4a08ea8e2b3c
Create Date: 2019-09-02 01:45:02.043994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df093e4cc05f'
down_revision = '4a08ea8e2b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'email')
    # ### end Alembic commands ###
