"""empty message

Revision ID: fa1ecda879b5
Revises: df093e4cc05f
Create Date: 2019-09-02 04:04:15.603908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa1ecda879b5'
down_revision = 'df093e4cc05f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('selected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'selected')
    # ### end Alembic commands ###
